Makefile:password run

password:
	gcc main_v2.1.c functions.c -o PasswordManager_v2.1 2> /dev/null

run:
	./PasswordManager_v2.1

clean:
	rm PasswordManager_v2.1.o

cleanall:
	rm PasswordManager_v2.1 *.o