Makefile:password run

password:
	gcc main_v3.0.c functions.c -o PasswordManager_v3.0 2> /dev/null

run:
	./PasswordManager_v3.0

clean:
	rm PasswordManager_v3.0.o

cleanall:
	rm PasswordManager_v3.0 *.o